// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRzB_6deDg-Q7fcly4u5SC0ffxYGCnPg',
    appId: '1:942238332444:web:6b2bafc58e333a04d691d9',
    messagingSenderId: '942238332444',
    projectId: 'proyectodam-56a61',
    authDomain: 'proyectodam-56a61.firebaseapp.com',
    storageBucket: 'proyectodam-56a61.firebasestorage.app',
    measurementId: 'G-D6S2NG6KQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97Y7F5j-SM68W6lAL7XSFhmt7NTCm67c',
    appId: '1:942238332444:android:a6bf2ffb65bb8ee3d691d9',
    messagingSenderId: '942238332444',
    projectId: 'proyectodam-56a61',
    storageBucket: 'proyectodam-56a61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1tYd8JTgk0ZzKoj4ODUChRiy4V7bvyb4',
    appId: '1:942238332444:ios:2b87472f05daee77d691d9',
    messagingSenderId: '942238332444',
    projectId: 'proyectodam-56a61',
    storageBucket: 'proyectodam-56a61.firebasestorage.app',
    iosBundleId: 'com.example.damProyect',
  );
}
